### ISSUE TITLE
Feature Request: Show charging bolt next to battery percentage

### ISSUE THREAD

**Issue by diary001** [thebarbican19/BatteryBoi#10]
Show the charging bolt next to the battery percentage like on the newer iPhone's. it would be nice to know if my MacBook is actually charging or not.

**Comment by liqfx** [comment]
This would be a great feature!

**Comment by thebarbican19** [comment]
This has been added to the new version which is now available @diary001, and @liqfx, what great timing for your request!

Please close this issue if you are happy with the way it looks.

**Comment by thebarbican19** [comment]
Hey @diary001, @liqfx this has been confirmed to be added in the last version and is 100% resolved in the version I just pushed which is available if you check for updates. With that, I am closing this issue as it is resolved. 

Also if you didn't see, BatteryBoi launched on [Product Hunt](https://www.producthunt.com/posts/batteryboi-open-source) today. If you haven't voted already, please do! Thanks
