### ISSUE TITLE
Icon on Menu bar only show first letter of text 

### ISSUE THREAD

**Issue by emmanuel-th** [thebarbican19/BatteryBoi#11]
- Icon on Menu bar only show first letter of text 
- low power mode toggle not work only ask admin password and not switch 

Sonoma public beta 4

![Screenshot 2023-08-30 at 2 17 13 PM](https://github.com/thebarbican19/BatteryBoi/assets/22926816/52811128-605c-4963-85b7-d6639b6b3cad)

**Comment by drodmantras** [comment]
Same for me on ventura 13.6 
<img width="47" alt="Screenshot 2023-08-30 at 13 07 00" src="https://github.com/thebarbican19/BatteryBoi/assets/58110607/a2a11eb3-0b1c-41f7-ab6d-2624dbb7a7ec">

**Comment by thebarbican19** [comment]
Thanks, @emmanuel-th & @drodmantras. Just experienced this myself, it's caused when the percent hits 90+. I will have a fix for this today.

**Comment by thebarbican19** [comment]
Hey @emmanuel-th & @drodmantras, I don't know if you have updated yet but if not please do as this should be resolved. Please let me know otherwise or I will be closing this issue tomorrow (Friday). Thanks!

**Comment by drodmantras** [comment]
Updated today, issue resolved now it's showing ok, thanks again!
