### ISSUE TITLE
Feature Request: Toggle the app icon in the Menu Bar

### ISSUE THREAD

**Issue by Daniel-Berezhnoy** [thebarbican19/BatteryBoi#13]
A feature that will allow us to hide the BatterryBoi's icon from the Menu Bar, without quitting the app.

**Comment by thebarbican19** [comment]
Thanks @Daniel-Berezhnoy, stay tuned 👀

**Comment by thebarbican19** [comment]
@Daniel-Berezhnoy please close this ticket if this latest update addresses this for you.
