### ISSUE TITLE
Missing xcodeproj file

### ISSUE THREAD

**Issue by TheAbstractDev** [thebarbican19/BatteryBoi#16]
Hi !

I'd like to contribute to this project but there's no xcodeproj file 😅

How can I generate it ?

**Comment by thebarbican19** [comment]
@TheAbstractDev I have just added this to the repo, so you should be able to just clone it. I can't wait to see what you add.

**Comment by TheAbstractDev** [comment]
Nice ! Thanks for your reactivity !

**Comment by thebarbican19** [comment]
Hey @TheAbstractDev, completely unrelated, but BatteryBoi is on [Product Hunt](https://www.producthunt.com/products/batteryboi/launches) today. Please vote for your favorite battery app 🙏🏻
