### ISSUE TITLE
[Request] Show time estimate on hover

### ISSUE THREAD

**Issue by avviyah** [thebarbican19/BatteryBoi#19]
Would you consider showing the time remaining on hover of the menubar icon?

**Comment by thebarbican19** [comment]
It sounds like a good idea, I don't want it overwriting others' preferences of having the percent or no text at all. Do you have any suggestions?

**Comment by thebarbican19** [comment]
Hi @avviyah, I have just pushed a new version (2.2.2). Please check for a new update in the app and install the new version as this feature has been added, and I think you will be happy with the result, I know I certantly am! 

Please confirm you are happy with this by closing the issue. 

Also if you didn't see, BatteryBoi launched on [Product Hunt](https://www.producthunt.com/posts/batteryboi-open-source) today. If you haven't voted already, please do! Thanks
