### ISSUE TITLE
Battery popup not showing up when click on icon menubar

### ISSUE THREAD

**Issue by emmanuel-th** [thebarbican19/BatteryBoi#28]
Sonoma public beta 5 
https://github.com/thebarbican19/BatteryBoi/assets/22926816/f55cebcc-4c01-4c9c-97ae-7bb82510504d

**Comment by emmanuel-th** [comment]
more bug 

https://github.com/thebarbican19/BatteryBoi/assets/22926816/9297387f-521a-40c6-b30c-51308c6d343d

**Comment by thebarbican19** [comment]
Hi, I have just published a new version. This should resolve it. If it does please close the issue.
