### ISSUE TITLE
Battery percentage gets stuck

### ISSUE THREAD

**Issue by BienGudBoy** [thebarbican19/BatteryBoi#31]
![IMG_2778](https://github.com/thebarbican19/BatteryBoi/assets/96908843/fa99a81c-494f-420a-9e71-7dad01b85550)

Happened when I woke up, fixed itself when I restarted the app.

**Comment by thebarbican19** [comment]
Thanks, I will look into this.

**Comment by thebarbican19** [comment]
Hi @BienGudBoy, this should be resolved in the latest version. I will wait for comments that state otherwise, if there is non I will close this issue in 2 days. Thanks!

**Comment by BienGudBoy** [comment]
Yeah, we can wait for this.
