### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kannicht** [thebarbican19/BatteryBoi#32]
Hi,

I'd like to put my handy on the German translation. There is just one question for me to answer before:

Do you want the translation to be formal or more casual? In German we have two versions of "you", one being the formal "Sie" and the more casual "Du". 

I guess since BatteryBoi offers a fresh style the casual translation would be more appropriate. Which one do you want to see in the app @thebarbican19 ?

**Comment by thebarbican19** [comment]
Hi @kannicht, good question but the app is very informal so I will go with that. Thanks

**Comment by kannicht** [comment]
PR open #34
