### ISSUE TITLE
Rename the repository to `JoeBattery` or `joebattery`

### ISSUE THREAD

**Issue by jaroshevskii** [thebarbican19/BatteryBoi#4]
Only for reasons of consistency ta convenience in the future.

Also if people follow the old link they will be redirected to the new one by GitHub.

**Comment by thebarbican19** [comment]
To remove it would change the URL which is currently tied to a bunch of posts.

**Comment by jaroshevskii** [comment]
GitHub is pretty handy with this, it will automatically redirect old links to new repositories.

For example, I used to have a `repeat-cli` repository, but later I changed the name to `repify-cli`. If I follow the old link, I will still get the correct result.

In my case, these two links lead to the same repository:

- https://github.com/jaroshevskii/repeat-cli (old link)
- https://github.com/jaroshevskii/repify-cli

You can learn more about renaming a repository on [GitHub Docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository).

**Comment by thebarbican19** [comment]
Thanks! I just reverted it back to the old name as people seemed to like that more. So that resolves it, but that information is good to know.
