### ISSUE TITLE
Version 2.4.1 - The Birthday Update [INSTANT CRASH]

### ISSUE THREAD

**Issue by iKalamaZoo** [thebarbican19/BatteryBoi#48]
The version 2.4.1 which download name is BatteryBoi-v2.4.1.dmg can't even start in macOS Monterey 12.6.9 (21G726). The version 2.2.2 is still the more stable version with only 1 bug: it gets blurred at startup and right in front of all apps. To fix this issue we need to restart the app every sleep/wake up process.

Again: The version 2.4.1 which download name is BatteryBoi-v2.4.1.dmg can't even start in macOS Monterey 12.6.9 (21G726).
In Addition: Asked me to get access to my calendar events.

**Comment by thebarbican19** [comment]
Please stop opening new issues. There is already one related to this crash.
