### ISSUE TITLE
Issues with macbook air m2

### ISSUE THREAD

**Issue by Kirecom** [thebarbican19/BatteryBoi#5]
Hello!

I tested this app on macbook air m2, with notch.

1) app goes into memory, but no icon appears on the menu bar.
2) when I open it (while still present in memory) it opens a standalone window with the right percentage of memory and a toggle like "zoom".

This is the test I could made on a brand new macbook air m2... Let me know if you need more info on this issue!

Thanks

**Comment by thebarbican19** [comment]
Hey @Kirecom sorry for the issues. My wife has an m1 MacBook so I will test on hers today and make some tweaks.

**Comment by Kirecom** [comment]
Thanks, if you need some test let me know, I'll install a new build :)



Roberto

Kirecom
Il 11 ago 2023, 16:19 +0200, Joe Barbour ***@***.***>, ha scritto:

**Comment by thebarbican19** [comment]
@Kirecom, from other issues and feedback it seems like this one is resolved. Please update to the latest release and let me know if the problem persists. If not, thanks for the feedback and please consider donating to the project so I can keep making my way though feedback requests.
