### ISSUE TITLE
The app window is usually unable to display on MacOs 14.1.

### ISSUE THREAD

**Issue by biigthinker** [thebarbican19/BatteryBoi#56]
When I click the menu icon, the window fails to display. The window only appears momentarily if I am in the Mission Control window. :D Hoping for solving.

**Comment by biigthinker** [comment]
Reinstall it solve this issue, Best app used!!!! THX !!!!

**Comment by thebarbican19** [comment]
Glad it resolved it's self @biigthinker , stay tuned for a new version soon. If you wouldn't mind, please leave a review on [Product Hunt](https://www.producthunt.com/posts/batteryboi-open-source)

**Comment by biigthinker** [comment]
> Glad it resolved it's self @biigthinker , stay tuned for a new version soon. If you wouldn't mind, please leave a review on [Product Hunt](https://www.producthunt.com/posts/batteryboi-open-source)

Glad to do it !!
