### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by jaroshevskii** [thebarbican19/BatteryBoi#6]
Add for example MIT License, Apache License,  or any other open source license.

Having a LICENSE file can help establish trust and openness with regard to the project and its authors, which can be important when collaborating with other developers or when publicly distributing the project.

For more information, visit the GitHub Docs:

- [Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
- [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by thebarbican19** [comment]
Also if you have ideas on how to share or where to share in the open source community, I am all ears as I know nothing about the space.

**Comment by thebarbican19** [comment]
Hey @jaroshevskii , completely unrelated, but BatteryBoi is on [Product Hunt](https://www.producthunt.com/products/batteryboi/launches) today. Please vote for your favorite battery app 🙏🏻
