### ISSUE TITLE
When clicking on the indicator, the battery percentage re-renders when fully expanded.

### ISSUE THREAD

**Issue by FormalSnake** [thebarbican19/BatteryBoi#65]
<img width="486" alt="Screenshot 2023-12-15 at 15 08 28" src="https://github.com/thebarbican19/BatteryBoi/assets/90651091/0a0efdcf-d921-44c1-b968-404617d1e6c0">

When going to the state as shown in the screenshot, the battery indicator did it's animation twice.

also, I cannot scroll in the menu using a mouse that doesn't have horizontal scrolling.

**Comment by thebarbican19** [comment]
Thanks for reporting. This however is a duplicate of another issue. 

I am working on 2 major issues, the next one will not address this as a redesign is coming to the following version.

**Comment by FormalSnake** [comment]
Thank you, I did not know it was a duplicate.

What did your last sentence mean though? I do not understand.

**Comment by thebarbican19** [comment]
Version 3.0 will have a new UI. This update will naturally resolve any issues regarding this UI and its functionality as scrolling and this animation will be removed or replaced. 

The next update v2.5 and subsequent smaller updates will continue to have this issue.

**Comment by FormalSnake** [comment]
Thank you, I will keep this in mind. I am overall enjoying BatteryBoi very much and I am thankful it exists.
