### ISSUE TITLE
1.0.2 no startup on Big Sur 11.7.9

### ISSUE THREAD

**Issue by bean-drew** [thebarbican19/BatteryBoi#7]
Looks like a great little update to the battery indicator.

App 1.0.2 on Big Sur 11.7.9 on a late-2013 rMBP.

When attempting to run from my Applications folder I get a "JoeBattery cannot be opened because of a problem" error. 

Which is a great error message. They almost nailed it but still just shy of "because reasons".

If the OS generated problem report or portions thereof would be helpful I can provide.

Cheers

**Comment by thebarbican19** [comment]
Thanks @bean-drew. Yeah MacOS errors can be incredibly vague, 'because reasons' would actually be more useful. I know the issue and am working on a fix as issues related to all all earlier OS versions than 13.0. It should be resolved in the net update. Hopefully that takes care of it.

**Comment by thebarbican19** [comment]
Hi @bean-drew, I have just added a new [release](https://github.com/thebarbican19/BatteryBoi/releases/tag/Version1.1.0) which _should_ hopefully resolve this issue.

I do not have a machine running Big Sur, so if you can test this and let me know I would be grateful. Thanks.

**Comment by kostazzz** [comment]
It doesn't start on Big Sur

**Comment by thebarbican19** [comment]
@bean-drew & @kostazzz, my friends I need your help! I have published v2 but cannot test on Big Sur. Would you mind and let's see if we can close this issue once and for all?

**Comment by bean-drew** [comment]
Newest version (2.1) is working on Big Sur! Good stuff!

> @bean-drew & @kostazzz, my friends I need your help! I have published v2 but cannot test on Big Sur. Would you mind and let's see if we can close this issue once and for all?

**Comment by thebarbican19** [comment]
Great, thanks @bean-drew. I am closing this issue with a smile on my silly face.

**Comment by kostazzz** [comment]
Thanks, Joe. 
For me, the icon design is too bold.

I use Battery Indicator <https://apps.apple.com/lt/app/battery-indicator/id1206020918?mt=12> but there is no balanced distance between the bottom and the top. I advise you to use a line thickness of 1.5 pixels on retina screens imperceptibly, which does not fall into the pixel grid. The font should not be thick, but regular. Try to change it, maybe you'll like it.



Respect, 
Kostas
