### ISSUE TITLE
Feature: showing charging status along with time left / percentage

### ISSUE THREAD

**Issue by A125X** [thebarbican19/BatteryBoi#8]
Currently BatteryBoi displays charging status OR battery status changing in a few seconds, like this
 
![Group 18](https://github.com/thebarbican19/BatteryBoi/assets/91656458/be698777-47fd-4082-b3a6-b1704edb7f0d)

So when I want to check battery percentage I sometimes have to wait for a few seconds. Instead, something like this could be shown:

![Group 17](https://github.com/thebarbican19/BatteryBoi/assets/91656458/e3609178-5dc8-498d-bcae-6dd2b599e00b)

Which helps user to understand system status faster. It'd be nice to have a setting to enable this kind of view.

**Comment by thebarbican19** [comment]
Hi @A125X, this is now implemented in the newest release. This was a neat idea, thanks for sharing.
