### ISSUE TITLE
Graphical issue with external monitor

### ISSUE THREAD

**Issue by zaktolba7C** [thebarbican19/BatteryBoi#9]
![Capture d’écran 2023-08-17 à 09 01 26](https://github.com/thebarbican19/BatteryBoi/assets/127412068/99c20158-b5be-48ed-afd5-cfbf31511ef8)

This is how the icon looks on my external monitor, however it looks fine on the MacBook's screen
The monitor is 27 inches 1080p, the result is the same when I change to a lower resolution.
I am running macOS Sonoma

**Comment by thebarbican19** [comment]
Hey @zaktolba7C, I have just published v2, this should address this issue, but right now I do not have an external monitor so I am gonna need your help testing. Thanks

**Comment by zaktolba** [comment]
Hey, you're welcome. Glad to help!
Sorry again I couldn't test in time, thanks to you 👍🏻

**Comment by thebarbican19** [comment]
Thanks @zaktolba! No worries at all, take care and enjoy the app!

**Comment by thebarbican19** [comment]
Hey @zaktolba, completely unrelated, but BatteryBoi is on [Product Hunt](https://www.producthunt.com/products/batteryboi/launches) today. Please vote for your favorite battery app 🙏🏻
